### ISSUE TITLE
Problems on rendering the correct datasource on Logging Dashboard

### ISSUE THREAD

**Issue by Deepzima** [sighupio/fury-kubernetes-logging#71] opened 2022-04-14 17:06 UTC
Dear team,
I've opened this issue with @nutellinoit just to track this bug that hit the Logging Dash

**Briefing:**
I've installed this logging module at the version 2.0.0 on a eks cluster(
v1.19.15) that's have the FD at v1.5.1, In follow the list of all subv of all components:

```
versions:
  monitoring: v1.11.1
  logging: v2.0.0
  ingress: v1.9.1
```
**Describe the bug:**
When I try to use the new Logging Dashboard, all queries(widgets) throw a message error. Probably the default source in the dashboard schema is incorrect for this version of the monitoring module. 
In follow a screen of the error:
![Screenshot 2022-04-14 at 18 59 05](https://user-images.githubusercontent.com/3962355/163437660-216e3f08-a595-48ef-b60e-725dfb2f1378.png)

**Comment by nutellinoit** [comment] 2022-04-14 17:44
Thank you @Deepzima for the report!

**Comment by nutellinoit** [comment] 2022-05-05 08:24
I tried with the latest version of the Monitoring module and the problem is not happening on my side

**Comment by nutellinoit** [comment] 2022-06-22 10:23
Closing this issue since is not happening with the new monitoring module

**Closed by nutellinoit** 2022-06-22 10:23 UTC
Labels: help wanted
